python3 parser.py testcase1.txt "()(())(()())"
python3 parser.py testcase2.txt "((((()))))"
python3 parser.py testcase3.txt "Tree(2)"
python3 parser.py testcase3.txt "Tree(2,[,])"
python3 parser.py testcase3.txt "Tree(2,[Tree(3),Tree(2)])"